# Parking Violations Issued - Fiscal Year 2022
This dataset provides data on Parking Violations Issued between July 1, 2021 to June 30, 2022. In New York City, the fiscal year begins on July 1st of one calendar year and ends on June 30th of the following calendar year. Click here to find out more about the NYC Fiscal Year.

download dataset from: https://data.cityofnewyork.us/City-Government/Parking-Violations-Issued-Fiscal-Year-2022/7mxj-7a6y/about_data

In [1]:
import pandas as pd 
import os

In [4]:
# Load 5 columns of data
df = pd.read_parquet(
    "C:\\Users\\hamza\\Documents\\Github\\nyc_parking_violations_2022.parquet",
    columns=["Registration State", "Violation Description", "Vehicle Body Type", "Issue Date", "Summons Number"]
)

In [5]:
df.sample(10)

,Registration State,Violation Description,Vehicle Body Type,Issue Date,Summons Number
10920273,NY,70A-Reg. Sticker Expired (NYS),4DSD,03/22/2022,8833996980
423124,NY,53-Safety Zone,SUBN,07/22/2021,8796048256
8410885,NJ,PHTO SCHOOL ZN SPEED VIOLATION,UT,01/10/2022,4763790262
13050754,NY,50-Crosswalk,SUBN,05/05/2022,8995023417
12500612,NY,21-No Parking (street clean),4DSD,04/13/2022,8785021477
14904219,NY,38-Failure to Dsplay Meter Rec,4DSD,06/18/2022,8582084766
15202064,NY,20A-No Parking (Non-COM),SUBN,05/31/2022,8906913102
14116079,NY,PHTO SCHOOL ZN SPEED VIOLATION,SUBN,06/02/2022,4781333760
6635777,NY,<NA>,SUBN,11/26/2021,1484521900
13310268,NY,PHTO SCHOOL ZN SPEED VIOLATION,BUS,05/12/2022,4779362416

### Which parking violation is most commonly comitted by vehicles from various U.S states?
i.e., Print the most commonly comittied parking violation in each state

In [6]:
# Group by state and violations
violations_count = df.groupby(['Registration State', 'Violation Description']).size()

# add violations count to dataframe
violations_df = violations_count.reset_index(name='Count')

# Sort by violation count for each state
violations_df_sorted = violations_df.sort_values(by=['Registration State', 'Count'], ascending=[True, False])

# Choose only the highest violation count for each state
violations_by_state = violations_df_sorted.groupby('Registration State').first().reset_index()
violations_by_state

   Registration State           Violation Description  Count
0                  99                            <NA>  17550
1                  AB                  14-No Standing     22
2                  AK  PHTO SCHOOL ZN SPEED VIOLATION    125
3                  AL  PHTO SCHOOL ZN SPEED VIOLATION   3668
4                  AR  PHTO SCHOOL ZN SPEED VIOLATION    537
..                ...                             ...    ...
62                 VT  PHTO SCHOOL ZN SPEED VIOLATION   3024
63                 WA    21-No Parking (street clean)   3732
64                 WI                  14-No Standing   1639
65                 WV  PHTO SCHOOL ZN SPEED VIOLATION   1185
66                 WY    21-No Parking (street clean)    138

[67 rows x 3 columns]

### Which vehicle body types are most frequently involved in parking violations?

In [7]:
df.sample(10)

,Registration State,Violation Description,Vehicle Body Type,Issue Date,Summons Number
2629073,NY,21-No Parking (street clean),SUBN,08/12/2021,8953081210
2381799,NY,69-Fail to Dsp Prking Mtr Rcpt,VAN,08/24/2021,8900318561
3821530,NY,37-Expired Parking Meter,SUBN,09/16/2021,8940865765
9610073,NY,40-Fire Hydrant,SUBN,01/27/2022,8641392166
8563851,NJ,PHTO SCHOOL ZN SPEED VIOLATION,UT,01/26/2022,4766097051
13820807,MN,47-Double PKG-Midtown(Com Veh),TRAC,05/10/2022,8901751550
15019074,NJ,21-No Parking (street clean),SUBN,06/09/2022,8832848855
2707732,TX,38-Failure to Dsplay Meter Rec,SUBN,08/20/2021,8974721170
13890434,IN,84-Platform lifts in low posit,DELV,05/06/2022,8928639451
56150,NY,BUS LANE VIOLATION,SUBN,07/01/2021,4017976645